### GET PASSWORDS

GET http://{{ host }}/api/v1/passwords/9bb31730-de05-4626-8222-1e0d4a3061fc
Accept: application/json

### CREATE PASSWORD

PUT http://{{ host }}/api/v1/passwords
Content-Type: application/json

{
  "password": "testing_password",
  "description": "testing description password"
}

### CREATE PASSWORD

PUT http://{{ host }}/api/v1/passwords
Content-Type: application/json

{
  "id": "9bb31730-de05-4626-8222-1e0d4a3061fc",
  "password": "testing_password_replace",
  "description": "testing description password replace"
}

### DELETE PASSWORD

DELETE http://{{ host }}/api/v1/passwords/9bb31730-de05-4626-8222-1e0d4a3061fc
Content-Type: application/json
