### GET PASSWORDS

GET http://{{ host }}/api/v1/passwords/cfb11f3b-b048-43db-9686-619b345fff01
Accept: application/json

### CREATE PASSWORD

PUT http://{{ host }}/api/v1/passwords
Content-Type: application/json

{
  "password": "testing_password",
  "description": "testing description password"
}

### CREATE PASSWORD

PUT http://{{ host }}/api/v1/passwords
Content-Type: application/json

{
  "id": "cfb11f3b-b048-43db-9686-619b345fff01",
  "password": "testing_password_replace",
  "description": "testing description password replace",
  "collection": {
    "id": "7b602a1f-081e-4f07-aa1f-f1d74daec07c"
  }
}

### DELETE PASSWORD

DELETE http://{{ host }}/api/v1/passwords/9bb31730-de05-4626-8222-1e0d4a3061fc
Content-Type: application/json
